name: .NET Core
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.300
    - name: Nuget
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: |
        export SPOTIFY__BASEURL='${{ secrets.SPOTIFY__BASEURL }}';
        export SPOTIFY__PATHARTISTINFORMATION='${{ secrets.SPOTIFY__PATHARTISTINFORMATION }}';
        export SPOTIFY__PATHRECOMMENDATIONSBYGENRE='${{ secrets.SPOTIFY__PATHRECOMMENDATIONSBYGENRE }}';
        export SPOTIFY__TOKENURL='${{ secrets.SPOTIFY__TOKENURL }}';
        export SPOTIFY__CLIENTID='${{ secrets.SPOTIFY__CLIENTID }}';
        export SPOTIFY__CLIENTSECRET='${{ secrets.SPOTIFY__CLIENTSECRET }}';
        export LASTFM__API_KEY='${{ secrets.LASTFM__API_KEY }}';
        export LASTFM__REGISTERED_TO='${{ secrets.LASTFM_REGISTERED_TO }}';
        export LASTFM__SHARED_SECRET='${{ secrets.LASTFM_SHARED_SECRET }}';
        dotnet test --no-restore --verbosity normal
