name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.300
    - name: Nuget
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Testing
      run: echo ${{ secrets.SPOTIFY__BASEURL }}
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      env: 
        BASEURL: ${{ secrets.SPOTIFY__BASEURL }}
        PATHARTISTINFORMATION: ${{ secrets.SPOTIFY__PATHARTISTINFORMATION }}
        PATHRECOMMENDATIONSBYGENRE: ${{ secrets.SPOTIFY__PATHRECOMMENDATIONSBYGENRE }}
        TOKENURL: ${{ secrets.SPOTIFY__TOKENURL }}

