name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.300
    - name: Nuget
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Testing
      run: echo ${{ secrets.SPOTIFY__BASEURL }}
    - name: Test
      env: 
        BASEURL: ${{ secrets.SPOTIFY__BASEURL }}
        PATHARTISTINFORMATION: ${{ secrets.SPOTIFY__PATHARTISTINFORMATION }}
        PATHRECOMMENDATIONSBYGENRE: ${{ secrets.SPOTIFY__PATHRECOMMENDATIONSBYGENRE }}
        TOKENURL: ${{ secrets.SPOTIFY__TOKENURL }}
      run: export SPOTIFY__BASEURL='https://api.spotify.com/v1/';export SPOTIFY__PATHARTISTINFORMATION='artists?ids={0}';export SPOTIFY__PATHRECOMMENDATIONSBYGENRE='recommendations?market=BR&seed_genres={0}&limit=10';export SPOTIFY__TOKENURL='https://accounts.spotify.com/api/token'; dotnet test --no-restore --verbosity normal


